include: ['_albums']

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title:               Christopher Su
tagline:             Photos
url:                 http://christopher.su
paginate:            1
baseurl:             "/photo"

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Christopher Su
  url:               http://christopher.su
  email:             chris@christopher.su

exclude:
  - generate_photos.sh
  - generate_json.py
  - bower.json
  - README.md
  - assets/components/jquery/
  - assets/components/photoswipe/src
  - assets/components/photoswipe/bower.json
  - assets/components/photoswipe/Gruntfile.js
  - assets/components/photoswipe/LICENSE
  - assets/components/photoswipe/package.json
  - assets/components/photoswipe/photoswipe.json
  - assets/components/photoswipe/README.md
  - assets/components/photoswipe/dist/photoswipe.js
  - assets/components/photoswipe/dist/photoswipe-ui-default.js
  - assets/components/photoset-grid/bower.json
  - assets/components/photoset-grid/Gruntfile.js
  - assets/components/photoset-grid/index.html
  - assets/components/photoset-grid/jquery.photoset-grid.js
  - assets/components/photoset-grid/package.json
  - assets/components/photoset-grid/README.markdown
  - assets/components/photoset-grid/img/demo
  - assets/components/photoset-grid/img/sh-logo.png
  - assets/components/photoset-grid/css/scss