include: ['_albums']

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title:               Christopher Su
tagline:             Photos
url:                 http://christopher.su
paginate:            1
baseurl:             "/photo"

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Christopher Su
  url:               http://christopher.su
  email:             chris@christopher.su