# Permalinks
permalink: pretty

# Setup
title:               Christopher Su
tagline:             Photos
url:                 http://christopher.su
paginate:            1
baseurl:             "/photo"

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Christopher Su
  url:               http://christopher.su
  email:             chris@christopher.su

json_store: http://winterfell.christopher.su/json/

exclude:
  - scripts/
  - gen_albums.py
  - albums.json
  - README.md
  - bower.json